import bcrypt from "bcryptjs";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ADMIN_EMAIL = "admin@tradejournal.local";
const ADMIN_USERNAME = "admin";
const ADMIN_PASSWORD = "@silver0";

const trades = [
  {
    pair: "EURUSD",
    direction: "buy",
    status: "closed",
    result: "win",
    openDate: new Date("2026-05-06T08:15:00.000Z"),
    closeDate: new Date("2026-05-06T11:40:00.000Z"),
    entryPrice: "1.07325",
    exitPrice: "1.07890",
    lotSize: "0.25",
    stopLoss: "1.07080",
    takeProfit: "1.07900",
    profitLossAmount: "141.25",
    profitLossPercentage: "1.1800",
    riskRewardRatio: "2.3000",
    setupName: "London breakout",
    timeframe: "M15",
    session: "London",
    emotionBefore: "Tenang, menunggu breakout valid",
    emotionAfter: "Puas karena mengikuti plan",
    entryReason: "Breakout range Asia dengan retest support intraday.",
    exitReason: "Take profit tersentuh dekat resistance H1.",
    lessonLearned: "Validasi retest membuat entry lebih aman.",
    notes: "Trade sesuai plan, tidak perlu scaling berlebihan.",
  },
  {
    pair: "GBPUSD",
    direction: "sell",
    status: "closed",
    result: "loss",
    openDate: new Date("2026-05-08T13:10:00.000Z"),
    closeDate: new Date("2026-05-08T14:25:00.000Z"),
    entryPrice: "1.25680",
    exitPrice: "1.26010",
    lotSize: "0.20",
    stopLoss: "1.26000",
    takeProfit: "1.24990",
    profitLossAmount: "-66.00",
    profitLossPercentage: "-0.5500",
    riskRewardRatio: "2.1500",
    setupName: "Liquidity sweep reversal",
    timeframe: "M30",
    session: "NewYork",
    emotionBefore: "Sedikit FOMO setelah news",
    emotionAfter: "Kecewa karena entry terlalu cepat",
    entryReason: "Sweep high sebelumnya tapi candle konfirmasi belum close.",
    exitReason: "Stop loss kena saat price lanjut naik.",
    lessonLearned: "Tunggu candle close setelah sweep, jangan masuk terlalu dini.",
    notes: "News volatility masih tinggi.",
  },
  {
    pair: "USDJPY",
    direction: "buy",
    status: "closed",
    result: "win",
    openDate: new Date("2026-05-12T01:35:00.000Z"),
    closeDate: new Date("2026-05-12T05:20:00.000Z"),
    entryPrice: "156.22000",
    exitPrice: "156.84000",
    lotSize: "0.18",
    stopLoss: "155.94000",
    takeProfit: "156.85000",
    profitLossAmount: "111.60",
    profitLossPercentage: "0.9300",
    riskRewardRatio: "2.2100",
    setupName: "Trend continuation",
    timeframe: "H1",
    session: "Asia",
    emotionBefore: "Percaya diri karena trend jelas",
    emotionAfter: "Stabil",
    entryReason: "Higher low pada trend bullish H1.",
    exitReason: "Exit di area supply intraday.",
    lessonLearned: "Trend continuation bekerja baik saat pullback rapi.",
    notes: "Entry tidak perlu ditahan terlalu lama.",
  },
  {
    pair: "XAUUSD",
    direction: "sell",
    status: "closed",
    result: "win",
    openDate: new Date("2026-05-14T12:45:00.000Z"),
    closeDate: new Date("2026-05-14T15:05:00.000Z"),
    entryPrice: "2368.50000",
    exitPrice: "2358.20000",
    lotSize: "0.05",
    stopLoss: "2374.00000",
    takeProfit: "2358.00000",
    profitLossAmount: "515.00",
    profitLossPercentage: "4.2900",
    riskRewardRatio: "1.8700",
    setupName: "New York continuation",
    timeframe: "M15",
    session: "NewYork",
    emotionBefore: "Fokus menunggu rejection",
    emotionAfter: "Senang tapi tetap disiplin",
    entryReason: "Rejection supply M15 setelah USD menguat.",
    exitReason: "Target intraday tercapai sebelum close London.",
    lessonLearned: "Gold butuh sizing kecil karena volatility besar.",
    notes: "Risk terkendali dengan lot kecil.",
  },
  {
    pair: "AUDUSD",
    direction: "buy",
    status: "closed",
    result: "breakeven",
    openDate: new Date("2026-05-16T07:30:00.000Z"),
    closeDate: new Date("2026-05-16T09:00:00.000Z"),
    entryPrice: "0.66240",
    exitPrice: "0.66250",
    lotSize: "0.30",
    stopLoss: "0.66090",
    takeProfit: "0.66550",
    profitLossAmount: "3.00",
    profitLossPercentage: "0.0200",
    riskRewardRatio: "2.0000",
    setupName: "Range bounce",
    timeframe: "M30",
    session: "London",
    emotionBefore: "Netral",
    emotionAfter: "Tidak masalah karena market sideways",
    entryReason: "Bounce support range dengan rejection kecil.",
    exitReason: "Momentum lemah, exit manual dekat breakeven.",
    lessonLearned: "Range market butuh target lebih konservatif.",
    notes: "Tidak semua setup perlu dipaksakan sampai TP.",
  },
  {
    pair: "EURJPY",
    direction: "sell",
    status: "closed",
    result: "loss",
    openDate: new Date("2026-05-20T09:05:00.000Z"),
    closeDate: new Date("2026-05-20T11:30:00.000Z"),
    entryPrice: "168.12000",
    exitPrice: "168.52000",
    lotSize: "0.15",
    stopLoss: "168.50000",
    takeProfit: "167.30000",
    profitLossAmount: "-60.00",
    profitLossPercentage: "-0.5000",
    riskRewardRatio: "2.1600",
    setupName: "Supply rejection",
    timeframe: "H1",
    session: "London",
    emotionBefore: "Overconfident setelah win sebelumnya",
    emotionAfter: "Menerima loss sesuai risk",
    entryReason: "Reject supply tetapi struktur belum lower low.",
    exitReason: "Stop loss valid kena.",
    lessonLearned: "Jangan short sebelum struktur confirm bearish.",
    notes: "Loss masih sesuai risk plan.",
  },
  {
    pair: "USDCAD",
    direction: "buy",
    status: "closed",
    result: "win",
    openDate: new Date("2026-05-23T13:50:00.000Z"),
    closeDate: new Date("2026-05-23T17:10:00.000Z"),
    entryPrice: "1.36400",
    exitPrice: "1.37020",
    lotSize: "0.22",
    stopLoss: "1.36120",
    takeProfit: "1.37000",
    profitLossAmount: "136.40",
    profitLossPercentage: "1.1400",
    riskRewardRatio: "2.2100",
    setupName: "New York continuation",
    timeframe: "H1",
    session: "NewYork",
    emotionBefore: "Sabar menunggu pullback",
    emotionAfter: "Percaya diri meningkat",
    entryReason: "Continuation setelah break structure H1.",
    exitReason: "TP kena di resistance daily minor.",
    lessonLearned: "Pullback entry lebih nyaman untuk hold.",
    notes: "Setup bersih dan sesuai checklist.",
  },
  {
    pair: "NZDUSD",
    direction: "sell",
    status: "open",
    result: "open",
    openDate: new Date("2026-06-02T06:20:00.000Z"),
    closeDate: null,
    entryPrice: "0.61420",
    exitPrice: null,
    lotSize: "0.18",
    stopLoss: "0.61700",
    takeProfit: "0.60850",
    profitLossAmount: null,
    profitLossPercentage: null,
    riskRewardRatio: "2.0400",
    setupName: "Trend continuation",
    timeframe: "H4",
    session: "Asia",
    emotionBefore: "Tenang karena setup H4",
    emotionAfter: null,
    entryReason: "Lower high pada bearish trend H4.",
    exitReason: null,
    lessonLearned: null,
    notes: "Open position dummy untuk menguji status open.",
  },
  {
    pair: "EURGBP",
    direction: "buy",
    status: "closed",
    result: "win",
    openDate: new Date("2026-06-04T10:00:00.000Z"),
    closeDate: new Date("2026-06-04T13:15:00.000Z"),
    entryPrice: "0.84610",
    exitPrice: "0.84920",
    lotSize: "0.35",
    stopLoss: "0.84480",
    takeProfit: "0.84910",
    profitLossAmount: "108.50",
    profitLossPercentage: "0.9000",
    riskRewardRatio: "2.3800",
    setupName: "London breakout",
    timeframe: "M30",
    session: "London",
    emotionBefore: "Fokus pada range London",
    emotionAfter: "Senang karena eksekusi bersih",
    entryReason: "Breakout kecil dari consolidation London.",
    exitReason: "TP di resistance intraday.",
    lessonLearned: "Pair cross lebih lambat tapi teknikal jelas.",
    notes: "Trade nyaman untuk review setup breakout.",
  },
  {
    pair: "GBPJPY",
    direction: "sell",
    status: "closed",
    result: "loss",
    openDate: new Date("2026-06-06T14:05:00.000Z"),
    closeDate: new Date("2026-06-06T14:55:00.000Z"),
    entryPrice: "197.45000",
    exitPrice: "197.92000",
    lotSize: "0.10",
    stopLoss: "197.90000",
    takeProfit: "196.55000",
    profitLossAmount: "-47.00",
    profitLossPercentage: "-0.3900",
    riskRewardRatio: "2.0000",
    setupName: "Liquidity sweep reversal",
    timeframe: "M15",
    session: "NewYork",
    emotionBefore: "Agresif setelah lihat wick besar",
    emotionAfter: "Sadar entry kurang sabar",
    entryReason: "Sweep high tapi belum ada displacement bearish.",
    exitReason: "SL kena karena price lanjut bullish.",
    lessonLearned: "JPY pair volatil, butuh confirmation lebih kuat.",
    notes: "Contoh loss realistis untuk analytics.",
  },
  {
    pair: "EURUSD",
    direction: "sell",
    status: "closed",
    result: "win",
    openDate: new Date("2026-06-09T12:30:00.000Z"),
    closeDate: new Date("2026-06-09T16:00:00.000Z"),
    entryPrice: "1.08240",
    exitPrice: "1.07720",
    lotSize: "0.28",
    stopLoss: "1.08490",
    takeProfit: "1.07730",
    profitLossAmount: "145.60",
    profitLossPercentage: "1.2100",
    riskRewardRatio: "2.0800",
    setupName: "New York continuation",
    timeframe: "M30",
    session: "NewYork",
    emotionBefore: "Disiplin menunggu pullback",
    emotionAfter: "Puas karena tidak overtrade",
    entryReason: "Breakdown support London lalu pullback rejection.",
    exitReason: "TP dekat demand M30.",
    lessonLearned: "Entry setelah pullback memberi R:R bagus.",
    notes: "Trade penutup minggu yang solid.",
  },
];

async function main() {
  const passwordHash = await bcrypt.hash(ADMIN_PASSWORD, 12);

  const admin = await prisma.user.upsert({
    where: { email: ADMIN_EMAIL },
    update: {
      name: ADMIN_USERNAME,
      passwordHash,
      preferredCurrency: "USD",
    },
    create: {
      name: ADMIN_USERNAME,
      email: ADMIN_EMAIL,
      passwordHash,
      preferredCurrency: "USD",
    },
  });

  await prisma.trade.deleteMany({ where: { userId: admin.id } });
  await prisma.trade.createMany({
    data: trades.map((trade) => ({ ...trade, userId: admin.id })),
  });

  console.log(`Seeded ${trades.length} realistic dummy trades for ${ADMIN_USERNAME} (${ADMIN_EMAIL}).`);
  console.log("Login username: admin");
  console.log("Login password: @silver0");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
